

export const menuItemsData = [
    {
      id: 1,
      name: 'Mediterranean  Salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/580b57fbd9996e24bc43c0de.png',
    },
    {
      id: 2,
      name: 'Summer Asian Slaw',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/burger-png-33925.png',
    },
    {
      id: 3,
      name: 'Burger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/burger-png-33936.png',
    },
    {
      id: 4,
      name: 'white sauce pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/burger-png-33938.png',
    },
    {
      id: 5,
      name: 'butterfly pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/burger-png-33942.png',
    },
    {
      id: 6,
      name: 'tooty fruity bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/Coke.png',
    },
    {
      id: 7,
      name: 'granola cereal bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/granola cereal bowl.png',
    },
    {
      id: 8,
      name: 'palm bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/item1.png',
    },
    {
      id: 9,
      name: 'tigela smoothie',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/item2.png',
    },
    {
      id: 10,
      name: 'breakfast cereal',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/item3.png',
    },
    {
      id: 11,
      name: 'cuisine of hawaii',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/item4.png',
    },
    {
      id: 12,
      name: 'fried chicken',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/item5.png',
    },
    {
      id: 13,
      name: 'greek salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/item6.png',
    },
    {
      id: 14,
      name: 'hamburger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/item7.png',
    },
    
  ];